### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/spheroRobotMazeSolver1#1]
Hi @eduardorasgado , with your permission I open this new issue, I hope we can work well again, like we did with your other project, so I would like to know if you have something in your mind for this logo, any ideas?

Can you tell me o more to get inspired.

Greetings!

**Comment by eduardorasgado** [comment]
This project works with onmidirectional ball shape like robot. Some fun logo. a ball with a smile or something. The robot moves inside a maze, looking for scape, i could think in a 3d like square(but just its vertices) and having inside a circle. Have fun @zuurw !

**Comment by zuurw** [comment]
Ok I will try to do something nice.

**Comment by zuurw** [comment]
Hi @eduardorasgado, here are my designs for this project I get inspired in the bot and the maze, see if you like one of this.
I will try them in smaller sizes to see how they look.

Regards!

![proposal](https://user-images.githubusercontent.com/40801473/42805230-30840584-89a3-11e8-90f8-a4194f5a2e34.png)

**Comment by eduardorasgado** [comment]
Awesome bro! I like the one in the middle(#3) logo. It really looks very good. Send me a pull request @zuurw :1st_place_medal:
